"""OperationProof public library API."""

from .attestation import (
    ATTESTATION_CONTRACT,
    HMAC_SHA256_V1,
    SIGNATURE_CONTRACT,
    SIGNED_ATTESTATION_CONTRACT,
    AttestationSigner,
    AttestationVerificationResult,
    AttestationVerifier,
    HMACSHA256Signer,
    HMACSHA256Verifier,
    ProvenanceVerificationResult,
    SignatureVerificationResult,
    attestation_payload,
    build_attestation,
    canonical_attestation_json,
    sign_attestation,
    verify_attestation_integrity,
    verify_attestation_signature,
    verify_provenance_chain,
)
from .attestation import (
    GENESIS as ATTESTATION_GENESIS,
)
from .attestation_store import (
    AttestationStore,
    AttestationStoreError,
    AttestationStoreHead,
    MemoryAttestationStore,
    validate_attestation_store_head,
)
from .builder import build_final_proof, build_pre_proof
from .conformance import (
    CONFORMANCE_CONTRACT,
    ConformanceScenario,
    ProviderConformanceCase,
    ProviderConformanceCaseResult,
    ProviderConformanceError,
    ProviderConformanceReport,
    run_provider_conformance,
)
from .domain import EvidenceEnvelope, Layer, ProofDecision, Verdict
from .execution import (
    ExecutionEffect,
    ExecutionOutcome,
    ExecutionReceiptVerificationResult,
    build_execution_receipt,
    verify_execution_receipt,
)
from .gateway_contract import (
    GATEWAY_TARGET_CONTRACT,
    GatewayTarget,
    GatewayTargetError,
    build_gateway_target,
    canonical_gateway_headers,
    gateway_target_digest,
)
from .gateway_store import (
    GatewayAdmissionRecord,
    GatewayAdmissionStore,
    GatewayAdmissionStoreError,
    MemoryGatewayAdmissionStore,
)
from .observability import (
    OBSERVABILITY_EVENT_CONTRACT,
    OBSERVABILITY_EVENT_TYPES,
    MemoryTelemetrySink,
    TelemetrySink,
    build_observability_event,
    emit_telemetry_best_effort,
)
from .provenance import (
    ProvenanceRecorder,
    ProvenanceRecorderError,
    ProvenanceRecordResult,
    attest_execution_receipt,
    attest_final_proof,
)
from .provider import (
    PROVIDER_ADAPTER_CONTRACT,
    AdapterOutputValidationResult,
    ProviderAdapterContractError,
    ProviderAdapterManifest,
    ProviderAdapterRegistry,
    validate_adapter_output,
)
from .sdk import (
    SDK_CONTRACT,
    ProofAssessment,
    ProofDocumentError,
    assess_proof,
    assess_proof_json,
    canonical_proof_json,
    parse_proof_json,
)
from .subject import OperationSubject, OperationSubjectError
from .subject_binding import (
    SubjectBindingError,
    bind_evidence_to_subject,
    make_subject_bound_trust_verifier,
)
from .trust import (
    ProviderTrustRegistry,
    TrustVerificationContext,
    TrustVerificationResult,
    verify_proof_trust,
)
from .verifier import VerificationResult, verify_proof

__all__ = [
    "ATTESTATION_CONTRACT",
    "ATTESTATION_GENESIS",
    "CONFORMANCE_CONTRACT",
    "GATEWAY_TARGET_CONTRACT",
    "HMAC_SHA256_V1",
    "OBSERVABILITY_EVENT_CONTRACT",
    "OBSERVABILITY_EVENT_TYPES",
    "PROVIDER_ADAPTER_CONTRACT",
    "SDK_CONTRACT",
    "SIGNATURE_CONTRACT",
    "SIGNED_ATTESTATION_CONTRACT",
    "AdapterOutputValidationResult",
    "AttestationSigner",
    "AttestationStore",
    "AttestationStoreError",
    "AttestationStoreHead",
    "AttestationVerificationResult",
    "AttestationVerifier",
    "ConformanceScenario",
    "EvidenceEnvelope",
    "ExecutionEffect",
    "ExecutionOutcome",
    "ExecutionReceiptVerificationResult",
    "GatewayAdmissionRecord",
    "GatewayAdmissionStore",
    "GatewayAdmissionStoreError",
    "GatewayTarget",
    "GatewayTargetError",
    "HMACSHA256Signer",
    "HMACSHA256Verifier",
    "Layer",
    "MemoryAttestationStore",
    "MemoryGatewayAdmissionStore",
    "MemoryTelemetrySink",
    "OperationSubject",
    "OperationSubjectError",
    "ProofAssessment",
    "ProofDecision",
    "ProofDocumentError",
    "ProvenanceRecordResult",
    "ProvenanceRecorder",
    "ProvenanceRecorderError",
    "ProvenanceVerificationResult",
    "ProviderAdapterContractError",
    "ProviderAdapterManifest",
    "ProviderAdapterRegistry",
    "ProviderConformanceCase",
    "ProviderConformanceCaseResult",
    "ProviderConformanceError",
    "ProviderConformanceReport",
    "ProviderTrustRegistry",
    "SignatureVerificationResult",
    "SubjectBindingError",
    "TelemetrySink",
    "TrustVerificationContext",
    "TrustVerificationResult",
    "Verdict",
    "VerificationResult",
    "assess_proof",
    "assess_proof_json",
    "attest_execution_receipt",
    "attest_final_proof",
    "attestation_payload",
    "bind_evidence_to_subject",
    "build_attestation",
    "build_execution_receipt",
    "build_final_proof",
    "build_gateway_target",
    "build_observability_event",
    "build_pre_proof",
    "canonical_attestation_json",
    "canonical_gateway_headers",
    "canonical_proof_json",
    "emit_telemetry_best_effort",
    "gateway_target_digest",
    "make_subject_bound_trust_verifier",
    "parse_proof_json",
    "run_provider_conformance",
    "sign_attestation",
    "validate_adapter_output",
    "validate_attestation_store_head",
    "verify_attestation_integrity",
    "verify_attestation_signature",
    "verify_execution_receipt",
    "verify_proof",
    "verify_proof_trust",
    "verify_provenance_chain",
]
