"""OperationProof public library API."""

from .attestation import (
    ATTESTATION_ALGORITHM_ED25519,
    PROVENANCE_STATEMENT_SCHEMA,
    SIGNED_ATTESTATION_SCHEMA,
    AttestationChainVerificationResult,
    AttestationError,
    AttestationSigner,
    AttestationTrustError,
    AttestationTrustRegistry,
    AttestationVerificationResult,
    Ed25519AttestationSigner,
    ProvenanceArtifactType,
    build_execution_receipt_provenance_statement,
    build_proof_provenance_statement,
    build_provenance_statement,
    sign_provenance_statement,
    verify_attestation_chain,
    verify_provenance_statement,
    verify_signed_attestation,
)
from .builder import build_final_proof, build_pre_proof
from .conformance import (
    CONFORMANCE_CONTRACT,
    ConformanceScenario,
    ProviderConformanceCase,
    ProviderConformanceCaseResult,
    ProviderConformanceError,
    ProviderConformanceReport,
    run_provider_conformance,
)
from .domain import EvidenceEnvelope, Layer, ProofDecision, Verdict
from .execution import (
    ExecutionEffect,
    ExecutionOutcome,
    ExecutionReceiptVerificationResult,
    build_execution_receipt,
    verify_execution_receipt,
)
from .gateway_contract import (
    GATEWAY_TARGET_CONTRACT,
    GatewayTarget,
    GatewayTargetError,
    build_gateway_target,
    canonical_gateway_headers,
    gateway_target_digest,
)
from .gateway_store import (
    GatewayAdmissionRecord,
    GatewayAdmissionStore,
    GatewayAdmissionStoreError,
    MemoryGatewayAdmissionStore,
)
from .observability import (
    OBSERVABILITY_EVENT_SCHEMA,
    MemoryTelemetrySink,
    ObservabilityEmitResult,
    ObservabilityError,
    ObservabilityEventType,
    TelemetrySink,
    TelemetrySinkError,
    assess_proof_observed,
    build_observability_event,
    emit_observability_event,
    verify_observability_event,
)
from .provider import (
    PROVIDER_ADAPTER_CONTRACT,
    AdapterOutputValidationResult,
    ProviderAdapterContractError,
    ProviderAdapterManifest,
    ProviderAdapterRegistry,
    validate_adapter_output,
)
from .sdk import (
    SDK_CONTRACT,
    ProofAssessment,
    ProofDocumentError,
    assess_proof,
    assess_proof_json,
    canonical_proof_json,
    parse_proof_json,
)
from .subject import OperationSubject, OperationSubjectError
from .subject_binding import (
    SubjectBindingError,
    bind_evidence_to_subject,
    make_subject_bound_trust_verifier,
)
from .trust import (
    ProviderTrustRegistry,
    TrustVerificationContext,
    TrustVerificationResult,
    verify_proof_trust,
)
from .verifier import VerificationResult, verify_proof

__all__ = [
    "ATTESTATION_ALGORITHM_ED25519",
    "CONFORMANCE_CONTRACT",
    "GATEWAY_TARGET_CONTRACT",
    "OBSERVABILITY_EVENT_SCHEMA",
    "PROVENANCE_STATEMENT_SCHEMA",
    "PROVIDER_ADAPTER_CONTRACT",
    "SDK_CONTRACT",
    "SIGNED_ATTESTATION_SCHEMA",
    "AdapterOutputValidationResult",
    "AttestationChainVerificationResult",
    "AttestationError",
    "AttestationSigner",
    "AttestationTrustError",
    "AttestationTrustRegistry",
    "AttestationVerificationResult",
    "ConformanceScenario",
    "Ed25519AttestationSigner",
    "EvidenceEnvelope",
    "ExecutionEffect",
    "ExecutionOutcome",
    "ExecutionReceiptVerificationResult",
    "GatewayAdmissionRecord",
    "GatewayAdmissionStore",
    "GatewayAdmissionStoreError",
    "GatewayTarget",
    "GatewayTargetError",
    "Layer",
    "MemoryGatewayAdmissionStore",
    "MemoryTelemetrySink",
    "ObservabilityEmitResult",
    "ObservabilityError",
    "ObservabilityEventType",
    "OperationSubject",
    "OperationSubjectError",
    "ProofAssessment",
    "ProofDecision",
    "ProofDocumentError",
    "ProvenanceArtifactType",
    "ProviderAdapterContractError",
    "ProviderAdapterManifest",
    "ProviderAdapterRegistry",
    "ProviderConformanceCase",
    "ProviderConformanceCaseResult",
    "ProviderConformanceError",
    "ProviderConformanceReport",
    "ProviderTrustRegistry",
    "SubjectBindingError",
    "TelemetrySink",
    "TelemetrySinkError",
    "TrustVerificationContext",
    "TrustVerificationResult",
    "Verdict",
    "VerificationResult",
    "assess_proof",
    "assess_proof_json",
    "assess_proof_observed",
    "bind_evidence_to_subject",
    "build_execution_receipt",
    "build_execution_receipt_provenance_statement",
    "build_final_proof",
    "build_gateway_target",
    "build_observability_event",
    "build_pre_proof",
    "build_proof_provenance_statement",
    "build_provenance_statement",
    "canonical_gateway_headers",
    "canonical_proof_json",
    "emit_observability_event",
    "gateway_target_digest",
    "make_subject_bound_trust_verifier",
    "parse_proof_json",
    "run_provider_conformance",
    "sign_provenance_statement",
    "validate_adapter_output",
    "verify_attestation_chain",
    "verify_execution_receipt",
    "verify_observability_event",
    "verify_proof",
    "verify_proof_trust",
    "verify_provenance_statement",
    "verify_signed_attestation",
]
